#! /bin/sh
# --- INICIO DE PROCESOS ---
# Lanzar sxhkd si no está corriendo
pgrep -x sxhkd > /dev/null || sxhkd &

# Configuración del teclado y cursor
setxkbmap -I$HOME/.config/xkb -layout es60 -option srvrkeys:none &
xsetroot -cursor_name left_ptr &

# Fondo de pantalla
feh --bg-scale /home/comandre/.fondo.png &

# --- MONITORES Y ESCRITORIOS ---
# Usamos números romanos para que Polybar los reconozca
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# --- CONFIGURACIÓN DE VENTANAS ---
bspc config border_width         0
bspc config window_gap           0
bspc config split_ratio          0.27
# Configuración de modo monocle
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# --- COLORES DE BORDES ---
bspc config normal_border_color  "#44475a"
bspc config active_border_color  "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"

# --- REGLAS DE APLICACIONES ---
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# --- SCRIPTS Y SERVICIOS ---
# Primero cargamos recursos de X
xrdb ~/.Xresources &


# --- Eliminar padding reservado para barras ---
bspc config top_padding 50
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config window_gap 8

# Otros servicios
xbindkeys --poll-rc &

bspc rule -a "Eww:bar" state=floating sticky=true focus=offbspc rule -a "Eww:bar" state=floating sticky=true focus=off
bspc config window_gap 8

picom --config ~/.config/picom/picom.conf &


killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 0.3; done
polybar main -c ~/.config/polybar/config.ini &

[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap &
