[module/arch]
type = custom/text
format = <label>
label = " ARCH "
label-foreground = ${colors.arch-blue}
label-padding = 2

[module/bspwm]
type = internal/bspwm
format = <label-state>
enable-click = true
enable-scroll = true
pin-workspaces = true
show-empty = true

ws-icon-0 = 1;1
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5
ws-icon-5 = 6;6
ws-icon-6 = 7;7
ws-icon-7 = 8;8
ws-icon-8 = 9;9
ws-icon-9 = 10;10

label-focused = ●
label-focused-foreground = ${colors.yellow}
label-focused-background = ${colors.card-active}
label-focused-padding = 2

label-occupied = ●
label-occupied-foreground = ${colors.purple}
label-occupied-padding = 1

label-empty = ●
label-empty-foreground = ${colors.gray}
label-empty-padding = 1

label-separator = " "

; 🪟 TÍTULO LIMPIO (Solo app, sin ruta. Solución 100% lado Polybar)
[module/xwindow]
type = custom/script
exec = xdotool getactivewindow getwindowname 2>/dev/null | sed 's|.*/||' | head -c 22 || echo BSPWM
interval = 1
label = %output%
label-empty = BSPWM
label-empty-foreground = ${colors.gray}

[module/wifi]
type = internal/network
interface-type = wireless
interval = 3
format-connected = <label-connected>
label-connected = " %essid% "
label-connected-foreground = ${colors.yellow}
format-disconnected = <label-disconnected>
label-disconnected = "✗ OFF "
label-disconnected-foreground = ${colors.gray}

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = true
interval = 1
format = <label>
format-background = ${colors.bg}
label = " VOL %percentage%% "
label-foreground = ${colors.fg}
label-muted = " MUTE "
label-muted-foreground = ${colors.red}
click-left = pavucontrol &
click-right = pavucontrol &
scroll-up = pactl set-sink-volume @DEFAULT_SINK@ +5% &
scroll-down = pactl set-sink-volume @DEFAULT_SINK@ -5% &

[module/clock]
type = internal/date
interval = 1
date = "%I:%M %p"
label = %date%
label-foreground = ${colors.yellow}
label-padding = 2

[module/vpn]
type = custom/script
exec = bash ~/.config/polybar/scripts/vpn_ip.sh
interval = 5
label = %output%
label-foreground = ${colors.yellow}
label-maxlen = 0

[module/sep]
type = custom/text
format = "│"
format-foreground = ${colors.gray}
format-background = ${colors.bg}

[module/powermenu]
type = custom/text
format = "⏻"
format-foreground = ${colors.red}
format-background = ${colors.bg}
format-padding = 0
click-left = ~/.config/polybar/scripts/power.sh
